### ISSUE TITLE
boilerplate image should include the ecc binary

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#103]
Currently the bilerplate image does not include the ecc binary because it requires mrenclave.go, which is available only after the chaincode enclave is compiled. So ecc is built after the chaincode enclave and then added to the final docker image.

**Comment by g2flyer** [comment]
One way to address that is to load mrenclave from a text-file instead of baking it into the code.  But bigger question for me is why would ecc need mrenclave baked into it? It always can get it at runtime if needed and ecc is not trusted anyway, so it's not really a trust question of baking it in?

**Comment by mbrandenburger** [comment]
this is why ecc has mrenclave baked in:

when a private chaincode is instantiated, mrenclave is written to the ledger as part of the chaincodes genesis block. Thus, this defines the code running in the enclave. At this time there is no enclave spawned which we could ask for its mrenclave.

As you said, ecc is untrusted but the client who instantiates the chaincode "can" verify that the writeset actually contains "the" expected mrenclave before submitting the transaction proposal response to the ordering service. Having a proper endorsement in place would also enable to detect a bad peer writing a "wrong" mrenclave into the chaincode's genesis block.

Our custom vscc for ercc relies on mrenclave in order to verifiy that an enclave is registered running the expected code. However, this is TBD as we may change to normal endorsement model here.

With new lifecycle in place mrenclave should be part of the chaincode definition and thus must be approved by the consortium.

**Comment by g2flyer** [comment]
> this is why ecc has mrenclave baked in:
> 
> when a private chaincode is instantiated, mrenclave is written to the ledger as part of the chaincodes genesis block. Thus, this defines the code running in the enclave. At this time there is no enclave spawned which we could ask for its mrenclave.
> 
> As you said, ecc is untrusted but the client who instantiates the chaincode "can" verify that the writeset actually contains "the" expected mrenclave before submitting the transaction proposal response to the ordering service. Having a proper endorsement in place would also enable to detect a bad peer writing a "wrong" mrenclave into the chaincode's genesis block.
> 
> Our custom vscc for ercc relies on mrenclave in order to verifiy that an enclave is registered running the expected code. However, this is TBD as we may change to normal endorsement model here.
> 
> With new lifecycle in place mrenclave should be part of the chaincode definition and thus must be approved by the consortium.

I guess i miss something above but i still don't see why MRENCLAVE (of PFC chaincode) has to be baked into ecc.    Ultimately, the end-user (or depending on trust-model, her org's peer) have to validate that a transaction is coming from an approved enclave and that this enclave has only engaged with the same type of enclave for key-management and only engaged with approved TLCC enclaves based on the agreed root-block of the ledger.   If peer verifies, then FPC MRENCLAVE should be part of the "FPC-CC-specific contract genesis block)", i.e., on the ledger and not in the code.  If client verifies, then the FPC MRENCLAVE doesn't even have to be on the ledger.    The more interesting case seems to me TLCC MRENCLAVE and the channel genesis block the TLCC uses which also must be implied in the FPC transaction signature.     For that baking in TLCC MRENCLAVE into FPC _enclave_ code could be one way although binding that as a parameter in the FPC init code or alike seems more flexible and could also handle the same way the channel genesis block (which would have to implied/verified also in the TLCC-FPC attestated secure channel.   Anyway, probably something to discuss at F2F with a white board (at least it was already on my list even before this discussion :-)

**Comment by g2flyer** [comment]
Closing this as the main part is really done and the subsequent discussion on why MRENCLAVE is needed (or not) in ecc doesn't seem worth to keep this issue open
