### ISSUE TITLE
Port/Remove Fabric Patches from FPC Build process

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#246]
Patches in `fabric/*.patch` are not compatible with Fabric 2.0. 

Discussion:
* Patch on MockChaincodeStub maybe just needs to be rebased
* Proxy still needed?
* SGX enablement for docker ? - not needed anymore as we move to external builder

Precondition: #255 closed

**Comment by g2flyer** [comment]
SGX should not be needed in long run (due to EB) and in short run we can just limit ourself to sim mode.  Proxy should not be need for us in long-run (due to EB) but if it would port with little effort probably still worth keeping for now. MockChainCodeStub is now in a different repo, so that would need more changes.  I have the TODO to try to get that also as an official Fabric PR, just was a bit on the sideline due to higher priority stuff ...

**Comment by g2flyer** [comment]
btw: a precondition of above is of course figuring out what changes in our build instructions we have to do get the v2 binaries (peer, configtxgen, cryptogen, orderer) we need for ledger created it in our integration tests (fabric/bin/lib/*, integration/*sh) ...

**Comment by mbrandenburger** [comment]
Patch on MockChaincodeStub not needed anymore as already integrated in Fabric. See #252

**Comment by mbrandenburger** [comment]
#266 updates the proxy patch

**Comment by mbrandenburger** [comment]
#270 removes the Mock and docker patch

**Comment by mbrandenburger** [comment]
With #266 this is closed
