### ISSUE TITLE
FPC Chaincode: Non-upgradability

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#313]
**Is your feature request related to a problem? Please describe.**

This is a non-feature, i.e., not supporting chaincode upgrading.  The reason for it is that it might help side-step the issue that ERCC might not be able to read directly a chaincode definition of a FPC chaincode from the ledger and hence doesn't know what the valid FPC version=MRENCLAVE is. But not allowing upgrades, admins can to verify the (single) enclave and the correctness of its MRENCLAVE (as visible in the attestation report). They would only engage in that chaincode if satisfied. Without upgrades, this correctness check would be an invariant holding also in the future. 

**Additional context**

See issue #312 for sibling feature

**Comment by bvavala** [comment]
For the record and for future discussions, here is a possible reasonable solution to the problem.

1. implement a chaincode approval mechanism in ERCC, so that organizations pre-approve the new chaincode in the enclave registry, before installing and approving it on the channel. This does not require changes to Fabric, but it duplicates the approval mechanism in ERCC.
2. implement and run a key transfer mechanism from the old (though still installed) chaincode enclave to the new one, based on the info in ERCC. The key transfer mechanism should be similar to the key distribution mechanism described in the FPC design documents. As usual, ERCC data is validated through the trusted ledger, and the key transfer collateral is validated and stored by ERCC.
3. perform the chaincode upgrade in Fabric, with the approval of all organizations. This makes the new chaincode ready to receive invocation in the channel.
4. complete the key transfer to the new chaincode (enclave) -- which otherwise would not be able to serve requests.

**Comment by g2flyer** [comment]
Wouldn't you have to at swap (at least partially) the order of 2. and 3.? Seems to me you have to first install the new chaincode and start with the lifecycle commands before you can create the enclave and hence start a key-transfer? So there would have to be some interleaving of the normal approve and the ercc approves before you then could do the ercc and cc commits, respectively?   Depends of course a bit on what atomicity guarantees you want in terms of switch-over.

**Comment by bvavala** [comment]
> Wouldn't you have to at swap (at least partially) the order of 2. and 3.? Seems to me you have to first install the new chaincode and start with the lifecycle commands before you can create the enclave and hence start a key-transfer? So there would have to be some interleaving of the normal approve and the ercc approves before you then could do the ercc and cc commits, respectively? Depends of course a bit on what atomicity guarantees you want in terms of switch-over.

It does not seem necessary. Yes, you have to install the new chaincode in order to create the enclave, but at that point you "terminate" the key transfer. As with the key distribution, the idea is to perform the key transfer in 2 steps: (1) the old chaincode packages the key for some enclave, and, for security reasons, you want some info in ERCC; (2) after installing the new chaincode, you complete the key transfer in the new enclave.

Also, by leveraging ERCC and TLCC we can control the switch-over. For instance, the commitment of a "key-transfer" transaction might mark the point in time, when the old chaincode stops undertaking further transitions, and the new chaincode begins undertaking transitions.  

> PS: another aspect which is not 100% clear is what restriction we might have to place on (lifecycle) endorsement policies, e.g., could we still support cc-specific policies (rather than global ones) and allow changing them? Might be possible but seems tricky. To be on safe side we might have to fix the policies to be the same and unchangeable?

Agreed, it's another aspect, which probably deserves its own separate discussion.

> PS(2): maybe worth mentioning here (and somewhat missing in the original description) is that the challenge is doing so without changing anything in the peer core. Once we start duplicating functionality in our own code to functionality already existing in the peer we get into the same problem space of TLCC and (non-)reusability of validation code with the main question being on what is the top-over point justifying some changes inside fabric proper (obviously also depending on how intrusive these changes are ...)

right

**Comment by g2flyer** [comment]
Hmm, but before you can your step one of the key-transfer, you would need the registered enclave for the new code? That's why i said you will to have to interleave the upgrade of the chaincode with your ercc upgrade/approval process? Otherwise you have a chicken'n'egg problem if you want to truly serialized.  
Also, regarding endorsement policy consistencies/constraints, this would be crucial for the correctness of the CC upgrade. So not really orthogonal?

**Comment by bvavala** [comment]
> Hmm, but before you can your step one of the key-transfer, you would need the registered enclave for the new code? That's why i said you will to have to interleave the upgrade of the chaincode with your ercc upgrade/approval process? Otherwise you have a chicken'n'egg problem if you want to truly serialized.

That's right. It will be up to the admin to locally grab the new enclave registration, before the new chaincode definition is actually committed.

> Also, regarding endorsement policy consistencies/constraints, this would be crucial for the correctness of the CC upgrade. So not really orthogonal?

1. Certainly true for ERCC (both the lifecycle and the chaincode policies).
2. not sure that Fabric allows for cc-specific lifecycle policies - I believe it does not.
3. with the implementation of the approval mechanism in ERCC, we can enable "fpc-specific lifecycle policies" which clearly rely on 1.
