### ISSUE TITLE
Remove FPC_ATTESTATION_TYPE as a compile-time parameter

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#431]
**Is your feature request related to a problem? Please describe.**
The problem is that the `FPC_ATTESTATION_TYPE` is a compile-time parameter, which determines the (only) attestation type that can be used by the compiled project. Hence, if `epid_linkable` is defined, the compiled project will only be able to issue linkable epid attestations. If the user needs (and has the credentials for) an unlinkable attestation, then he is required to recompile FPC.

Summarizing, the attestation type is treated as a compile-time option, but it is really bound to the type of SPID that IAS provides.

**Describe the solution you'd like**
What I would suggest is to generalize the input SPID.
Instead of a file containing `ABD..33`, it would become `"{'linkable':true/false, spid_hex:'ABD...33'}"`.
Hence, the attestation type would be bound to the SPID itself, and provided as user input.

**Describe alternatives you've considered**
Alternatively, we attestation type could go into a separate `epid_type` file.

**Additional context**
Two remarks:
* the proposed solution generalizes EPID (it's orthogonal to DCAP)
* the problem could be better addressed probably as part of #412

**Comment by mbrandenburger** [comment]
I like your proposal making this a runtime option rather than a compile-time option. Having the spid file some more context makes sense and is easy to implement. Alternatively to using json, yaml would align a bit better (in my opinion) with other configuration files Fabric uses and might be easier for humans to edit.

I think this work item should be handled as port of #412.
