### ISSUE TITLE
Resolve whether "transactionalized `__invoke`" is an issue for MVP.

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#523]
**Description**

On slack and in #274/#275/#477 i pointed out that an adversary could run `__invoke` as a transaction.  This is clearly a problem for multi-endorser endorsement policies.  I think it would be a non-issue for designated chaincode policy with a single enclave, and probably not even with multiple enclaves, but we should investigate this a bit more to be on the safe side for MVP FPC 1.0 release.

**Link to feature or bug**

**Link to dependent issues**

**Comment by bvavala** [comment]
In our discussion, we determined that:
- nothing prevents an actor from packing and submitting the results of the `__invoke`, as received by the enclave, for ordering and commit, with the aim of circumventing the enclave signature verification step
- as we highlighted in documentation, and the [RFC](https://github.com/hyperledger/fabric-rfcs/pull/40), it is _strongly_ recommended that the FPC chaincode be installed/approved in the Fabric channel with a **strong** endorsement policy, for example: a majority of organizations have to endorse a transaction for this to be successfully committed to the ledger
- it is due to such strong endorsement policy (as opposed to "a single endorsement is sufficient"), that the `__invoke` transaction can be submitted for ordering, but _not_ successfully committed to the ledger. Hence, no unverified data, allegedly coming from an enclave, can be written to the ledger, as a result of a successful commit-and-validate step in the Fabric channel.
