### ISSUE TITLE
Images' links in README not working

### ISSUE THREAD

**Issue by saki-osive** [hyperledger-labs/fabric-private-chaincode#540]
The png image files in README don't seem to point to a working link.
Please verify if this is the case.
![missing-png-links-docs](https://user-images.githubusercontent.com/62865682/110784808-29049600-8290-11eb-8b79-d5c59143f3ef.png)

**Comment by bvavala** [comment]
@saki-osive you are technically right. The `png` files are not there because they must be derived from the `puml` files using PlantUML. See [Building Documentation](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/README.md#building-documentation).

If you have a suggestion to clarify this aspect, please consider pushing a PR.

**Comment by munapower** [comment]
Ok, I will create a PR for this and Fix it.
