### ISSUE TITLE
how to implement  access control model in FPC

### ISSUE THREAD

**Issue by TrueAbc** [hyperledger-labs/fabric-private-chaincode#542]
I hava found an anac model in [fabric-samples](https://github.com/hyperledger/fabric-samples/tree/master/asset-transfer-abac/chaincode-go/smart-contract), and I want to know how to use shim_ctx_ptr in chaincode to implement access control model like this(maybe store encrypted token in ctx).  And how to get remote attestation report or other crediential  of  enclave chaincode in FPC. Thanks in advance.
![image](https://user-images.githubusercontent.com/47651330/111056025-9c87ec80-84b6-11eb-8e53-f1622a0e8868.png)

**Comment by bvavala** [comment]
There are several things to answer here.

1. The `shim_ctx_ptr` maintains context information relative to the interaction between the Go code and the chaincode enclave, which allow to make downcalls from enclave. This is quite different from transaction contexts in Fabric. In general, FPC chaincode developers should use only use the interface as provided in the [shim](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/ecc_enclave/enclave/shim.h).

2. The ABAC example in Fabric is based on ClientIdentity and ultimately on the GetCreator, which cannot be securely supported in the current FPC implementation. In particular, FPC could (once implemented) extract identity-related information from the Fabric signed transaction proposal. However, FPC cannot validate such information against the roots of trust stored on the ledger -- because the ledger is outside the trusted computing base.

As an FPC chaincode developer, you can still develop this capability in chaincode. Your implementation should take into consideration the security properties provided by FPC. In particular, it should not release sensitive data conditioned on client identity/attribute stored on the ledger (see [comments in shim.h](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/feb9931b6ec02fc9c86af074bced0caa6fa5a4b8/ecc_enclave/enclave/shim.h#L25)).

3. Regarding the remote attestation and credentials, please check out the [FPC Enclave Registry chaincode](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/ercc/registry/registry.go) and the [credentials protobuf structure](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/protos/fpc/fpc.proto). The registry is a regular chaincode with a simple interface for retrieving enclave credentials, while the credentials include the evidence field which contain the publicly-verifiable verification report of the enclave.

**Comment by TrueAbc** [comment]
> 2. The ABAC example in Fabric is based on ClientIdentity and ultimately on the GetCreator, which cannot be securely supported in the current FPC implementation. In particular, FPC could (once implemented) extract identity-related information from the Fabric signed transaction proposal. However, FPC cannot validate such information against the roots of trust stored on the ledger -- because the ledger is outside the trusted computing base.
> 
> As an FPC chaincode developer, you can still develop this capability in chaincode. Your implementation should take into consideration the security properties provided by FPC. In particular, it should not release sensitive data conditioned on client identity/attribute stored on the ledger (see [comments in shim.h](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/feb9931b6ec02fc9c86af074bced0caa6fa5a4b8/ecc_enclave/enclave/shim.h#L25)).

So   in v1.0-rc1 FPC,  ```get_creator_name``` call like this would expose user data to untrusted memory?
![image](https://user-images.githubusercontent.com/47651330/112710000-edf19c00-8ef8-11eb-8695-5caaff56262a.png)

How about attaching metadata in request.  I think FPC  request data will  keep encrypted outside chaincode enclave?

**Comment by TrueAbc** [comment]
And If I want to transmit key-value args I can only transmit args list and parse in my chaincode enclave.
![image](https://user-images.githubusercontent.com/47651330/112710359-5fcae500-8efb-11eb-9c6a-bb531c05b1ac.png)

**Comment by mbrandenburger** [comment]
> So in v1.0-rc1 FPC, get_creator_name call like this would expose user data to untrusted memory?

well, the creator name is anyway a public part of the transaction proposal. Our current implementation of `get_creator_name` just consumes the "untrusted" [GetCreator()](https://github.com/hyperledger/fabric-chaincode-go/blob/main/shim/interfaces.go#L314) from the go chaincode API, thus, it is considered untrusted with v1.0-rc1 as Bruno already mentioned.

> And If I want to transmit key-value args I can only transmit args list and parse in my chaincode enclave.

correct, you just pass your data ([json or what ever](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/examples/auction/auction_json.cpp)) as string into the args and use it inside your chaincode enclave.
In the example you posted, just move the metadata into the Args:
```bash
peer chaincode invoke -C mychannel -n helloworld_test -c '{{"Function":"storeAsset", "Args": ["asset2", "100", "{\"somemetadata\": ........ }"]}}'
```

**Comment by TrueAbc** [comment]
Thanks a lot. I think it's enough to implement an access model.
