### ISSUE TITLE
refactor shim and chaincode interface

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#83]
the methods provided by `shim.h` should be revisited. Error handling is missing, for instance, `getState` does not return an error when a integrity violation is detected.

**Comment by mbrandenburger** [comment]
logging should be revisited as well #88

**Comment by mbrandenburger** [comment]
we also should refactor the chaincode interface, for instance, returning the arguments already as array instead of forcing the chaincode to unmarshal the args using json.

```
invoke(const char *args, uint8_t *response, uint32_t max_response_len, uint32_t *actual_response_len, void *ctx);
```

**Comment by g2flyer** [comment]
We should also clean up shim.h with internal functions not targeted to chaincode developers (e.g., all the rwset functions). They should be moved out of the shim to a separate header-file such that shim.h is exactly and only the complete external programming model.

**Comment by g2flyer** [comment]
If we have unmarshall functions for inputs in shim.h, shouldn't we have corresponding marshall functions for results? Seems strange to have only one but not the other ...

**Comment by g2flyer** [comment]
More long-term, but we probably also want to have some `put_public_state function` as discussed earlier

**Comment by g2flyer** [comment]
Shouldn't `shim.h` also contain some form of interface definition of functions which the chaincode has to implement, i.e.,
```
int invoke(const char* args,
    uint8_t* response,
    uint32_t max_response_len,
    uint32_t* actual_response_len,
    void* ctx)
{
```?

**Comment by g2flyer** [comment]
If we want enable client authentication based on MSP, we might also want to add a corresponding API function

**Comment by g2flyer** [comment]
eventually we want to benefit also from fabric private data collection. 

They definitely can give a performance boost when dealing with large data as the data doesn't have to go all to the orderer.  Enabling this, though, can be done under the cover and does not have to be exposed in the API.

Less clear is whether there are some scenario where we want to expose it to the developer the `{Get,Put}PrivateData*` which are in the normal Go Shim (https://godoc.org/github.com/hyperledger/fabric/core/chaincode/shim).  In their case of course it might be necessary due to some data being shared with chaincodes which are not part of the collection but for us it really shouldn't make a security difference (and hence following occam's razor i would not expose it).  Maybe iff we add a `PutPublic*` it might be slightly different as we would then have a somewhat semi-private setting (though we should then probably call it `PutPublicPrivate` or `PutSemiPublic` rather than the `PutPrivateData` ...

**Comment by g2flyer** [comment]
Close as remaining issues are delegated to issue #88 and #150
