### ISSUE TITLE
Dockerized build environment

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#99]

**Comment by mbrandenburger** [comment]
This linkes to CI enabling #48

**Comment by mbrandenburger** [comment]
SGX SDK 2.6 has introduced reproducible enclave builds. We should have a look and also use this here.

**Comment by mbrandenburger** [comment]
As fabric is moving to Alpine based docker images we cannot build our fabric-ccenv-sgx image from fabric-ccenv in the future.

It seems that Alpine is not supported to use with the SGX SDK caused by incompatibilities with MUSL.

However, we can still use Ubuntu as base image. To reduce image sizes multi-stage builds can be used.

**Comment by mbrandenburger** [comment]
This Issue also links to #32

**Comment by mbrandenburger** [comment]
PR #168 introduces a docker image to build FPC. However, this is just for convenient development and not the default way how to build the project.

**Comment by g2flyer** [comment]
> SGX SDK 2.6 has introduced reproducible enclave builds. We should have a look and also use this here.

This is captured in issue #114

**Comment by g2flyer** [comment]
Added some docu on docker dev image in PR #176 and hence close this
